# Generated by Django 2.1.5 on 2019-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('e_mail', models.EmailField(default='example@example.com', max_length=254)),
                ('text', models.TextField(default=' ')),
            ],
        ),
    ]
